CC =            gcc
NAME =          jena-dev
SRC =           *.c
CFLAGS =        -W -Wall -Wextra -Werror
OBJ =           
RM =            rm -rf
 :       
                   -o ../
                rm -rf *.o
                find ./ -name *.DS_Store
                find ./ -name *.DS_Store -delete
all:            
clean:
                 
fclean:         clean
re:             fclean
                make
