CC =            gcc
NAME =          jena-dev
SRC =           *.c

CFLAGS =        -W -Wall -Wextra -Werror
OBJ =           $(SRC:%.c=%.o)
RM =            rm -rf

$(NAME) :	$(OBJ)
		$(CC) $(SRC) $(CFLAGS) -o ../$(NAME)
		rm -rf *.o

all:		$(NAME)
clean:
		$(RM) $(OBJ)
fclean:		clean

re:		fclean
		make
